deployment

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,50 +1,96 @@
-name: Auto Deploy Streamlit App to AWS EC2
+name: Coffee Sales App
 
 on:
   push:
     branches:
-      - main  # or specify the branch to deploy from
+      - main
+
+permissions:
+  id-token: write
+  contents: read
 
 jobs:
-  build:
+  build-and-push-ecr-image:
+    name: Continuous Delivery
     runs-on: ubuntu-latest
-    
     steps:
-    - name: Checkout the code
-      uses: actions/checkout@v2
+      - name: Checkout Code
+        uses: actions/checkout@v3
+      
+      - name: Install Utilities
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jq unzip
 
-    - name: Log in to DockerHub
-      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
 
-    - name: Build Docker image
-      run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest .
-
-    - name: Push Docker image to DockerHub
-      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest
-
-  deploy:
-    needs: build
-    runs-on: ubuntu-latest
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
     
+      - name: Build, tag, and push image to Amazon ECR
+        id: build-image
+        env:
+          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
+          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
+          IMAGE_TAG: latest
+        run: |
+          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
+          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
+          echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG"
+
+  Continuous-Deployment:
+    needs: build-and-push-ecr-image
+    runs-on: self-hosted
     steps:
-    - name: Install SSH Client
-      run: sudo apt-get install -y openssh-client
+      - name: Checkout Code
+        uses: actions/checkout@v3
+  
+      - name: Configure AWS credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: ${{ secrets.AWS_REGION }}
+  
+      - name: Install Utilities
+        run: |
+          sudo apt-get update
+          sudo apt-get install -y jq unzip
+  
+      - name: Login to Amazon ECR
+        id: login-ecr
+        uses: aws-actions/amazon-ecr-login@v1
+    
+      - name: Ensure Docker is running
+        run: |
+          if ! sudo systemctl is-active --quiet docker; then
+            echo "Docker is not running, starting Docker..."
+            sudo systemctl start docker
+          fi
+          sudo systemctl status docker
 
-    - name: Set up SSH key for EC2 access
-      run: |
-        echo "${{ secrets.EC2_KEY }}" | base64 --decode > ec2_key.pem
-        chmod 400 ec2_key.pem
+      - name: Pull Docker Image
+        run: |
+          docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest || {
+            echo "Docker pull failed, attempting to restart Docker...";
+            sudo systemctl restart docker;
+            docker pull ${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest;
+          }
 
-    - name: SSH into EC2 and Deploy
-      run: |
-        ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
-          # Pull the latest Docker image from DockerHub
-          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest
-          
-          # Stop any existing container
-          docker stop streamlit-container || true
-          docker rm streamlit-container || true
-          
-          # Run the new container
-          docker run -d -p 8501:8501 --name streamlit-container ${{ secrets.DOCKERHUB_USERNAME }}/coffe-sales:latest
-        EOF
+      - name: Run Docker Image to Serve Users
+        run: |
+          export IMAGE_NAME="${{ secrets.AWS_ECR_LOGIN_URI }}/${{ secrets.ECR_REPOSITORY_NAME }}:latest"
+          export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
+          export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
+          export AWS_DEFAULT_REGION="${{ secrets.AWS_REGION }}"
+          docker compose up -d
+
+      - name: Docker System Prune to Remove Old Images
+        run: |
+          docker system prune -f
